import type { CSSProperties } from 'react';
import { canvasTheme } from '../theme/canvas-theme';

/** Layout and paint for the compact Stock canvas surface. */
export const cncStockCanvasHudStyles = {
  panel: {
    position: 'absolute',
    top: 56,
    left: 24,
    zIndex: 5,
    width: 300,
    maxWidth: 'calc(100% - 48px)',
    boxSizing: 'border-box',
    padding: 10,
    boxShadow: 'var(--lf-shadow)',
    pointerEvents: 'auto',
    fontFamily: 'var(--lf-font)',
    fontSize: 'var(--lf-text-md)',
  },
  collapsedPanel: {
    width: 176,
    padding: 4,
    background: 'color-mix(in srgb, var(--lf-bg-1) 68%, transparent)',
    borderColor: 'color-mix(in srgb, var(--lf-border-strong) 38%, transparent)',
    boxShadow: '0 3px 10px color-mix(in srgb, var(--lf-text) 10%, transparent)',
    backdropFilter: 'blur(6px)',
  },
  connector: {
    position: 'absolute',
    top: 120,
    left: '100%',
    width: 28,
    borderTop: `1px solid ${canvasTheme.stockStroke}`,
    pointerEvents: 'none',
  },
  connectorDot: {
    position: 'absolute',
    top: -3,
    right: -3,
    width: 6,
    height: 6,
    background: canvasTheme.stockStroke,
    borderRadius: '50%',
  },
  headerButton: {
    width: '100%',
    minWidth: 0,
    display: 'flex',
    alignItems: 'center',
    gap: 9,
    padding: 4,
    textAlign: 'left',
  },
  collapsedHeaderButton: { gap: 6, padding: 1 },
  stockIcon: {
    display: 'grid',
    placeItems: 'center',
    width: 28,
    height: 28,
    flexShrink: 0,
    color: canvasTheme.stockStroke,
    background: canvasTheme.stockFill,
    border: `1px solid ${canvasTheme.stockStroke}`,
    borderRadius: 'var(--lf-radius-md)',
  },
  headingText: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
    flex: 1,
  },
  title: { fontSize: 'var(--lf-text-lg)' },
  collapsedTitle: { fontSize: 'var(--lf-text-sm)', lineHeight: 1.1 },
  summary: {
    overflow: 'hidden',
    color: 'var(--lf-text-muted)',
    fontSize: 'var(--lf-text-sm)',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  collapsedSummary: { fontSize: 'var(--lf-text-xs)', lineHeight: 1.1 },
  body: {
    display: 'grid',
    gap: 12,
    marginTop: 8,
    padding: '12px 4px 2px',
    borderTop: '1px solid var(--lf-border)',
  },
  thicknessRow: {
    display: 'grid',
    gridTemplateColumns: '76px minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: 6,
  },
  pairGroup: { display: 'grid', gap: 5, minWidth: 0 },
  pairFields: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 8,
  },
  originRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) 58px',
    alignItems: 'end',
    gap: 12,
  },
  prefixedField: {
    display: 'grid',
    gridTemplateColumns: '16px minmax(0, 1fr)',
    alignItems: 'center',
    gap: 4,
  },
  groupLabel: {
    color: 'var(--lf-text-muted)',
    fontSize: 'var(--lf-text-sm)',
  },
  prefix: {
    color: 'var(--lf-text-faint)',
    fontSize: 'var(--lf-text-sm)',
  },
  unit: {
    color: 'var(--lf-text-faint)',
    fontSize: 'var(--lf-text-xs)',
  },
  input: { width: '100%', minWidth: 0, height: 30 },
  diagram: { color: 'var(--lf-text-faint)', overflow: 'visible' },
} satisfies Readonly<Record<string, CSSProperties>>;
