/**
 * T1-134: regression test for the pure GRBL job-line + OBJ-id marker
 * parser extracted from `GrblController._parseJobLines`. The parser
 * encodes the mapping rule between `; OBJ ids=...` comments emitted by
 * the Output strategy and the gcode lines that follow them — a contract
 * the controller relies on to translate per-line acks back to scene
 * object IDs for live progress reporting.
 *
 * Pre-T1-134 this 20-line method lived inside the 2664-line
 * GrblController. Exercising the grammar required mounting the whole
 * controller with a mock port; post-T1-134 every grammar branch is
 * pinned standalone.
 *
 * Run: npx tsx tests/grbl-job-line-parser.test.ts
 */
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseGrblJobLines } from '../src/controllers/grbl/GrblJobLineParser';

let passed = 0;
let failed = 0;

function assert(condition: unknown, message: string): void {
  if (condition) {
    passed++;
    console.log(`  PASS ${message}`);
  } else {
    failed++;
    console.error(`  FAIL ${message}`);
  }
}

console.log('\n=== T1-134 GRBL job-line + OBJ-id parser ===\n');

// -------- 1. empty + whitespace input --------
{
  const r = parseGrblJobLines([]);
  assert(r.jobLines.length === 0 && r.lineMarkers.length === 0,
    'empty input → empty output');
}
{
  const r = parseGrblJobLines(['', '   ', '\t', '\n']);
  assert(r.jobLines.length === 0,
    'whitespace-only lines are dropped');
}

// -------- 2. simple gcode lines (no markers) --------
{
  const r = parseGrblJobLines(['G0 X10', 'G1 X20', 'G0 X30']);
  assert(r.jobLines.length === 3 && r.lineMarkers.length === 3,
    'three gcode lines → three job entries');
  assert(r.lineMarkers.every((m) => m === null),
    'no markers → all lineMarkers null');
}

// -------- 3. lines are trimmed --------
{
  const r = parseGrblJobLines(['  G0 X10  ', '\tG1 Y5']);
  assert(r.jobLines[0] === 'G0 X10' && r.jobLines[1] === 'G1 Y5',
    'leading/trailing whitespace trimmed from each line');
}

// -------- 4. OBJ-id marker attaches to next gcode line --------
{
  const r = parseGrblJobLines([
    '; OBJ ids=a,b,c',
    'G0 X10',
    'G1 X20',
  ]);
  assert(r.jobLines.length === 2 && r.jobLines[0] === 'G0 X10',
    'marker is consumed (not pushed as a line)');
  assert(JSON.stringify(r.lineMarkers[0]) === '["a","b","c"]',
    'first gcode line carries the marker IDs');
  assert(r.lineMarkers[1] === null,
    'second gcode line carries no marker (marker consumed)');
}

// -------- 5. marker spacing tolerance --------
{
  const r = parseGrblJobLines([
    ';OBJ ids=alpha',
    'G0 X1',
    ';   OBJ   ids=beta,gamma',
    'G0 X2',
  ]);
  assert(JSON.stringify(r.lineMarkers[0]) === '["alpha"]',
    'marker without space after `;` is recognized');
  assert(JSON.stringify(r.lineMarkers[1]) === '["beta","gamma"]',
    'marker with extra spaces is recognized');
}

// -------- 6. marker case insensitivity --------
{
  const r = parseGrblJobLines([
    '; obj ids=X',
    'G0 X1',
    '; OBJ IDS=Y',
    'G0 X2',
  ]);
  assert(JSON.stringify(r.lineMarkers[0]) === '["X"]',
    'lowercase `obj ids=` recognized');
  // Note: the original regex is /^;\s*OBJ\s+ids=(.+)$/i so both case
  // variants are caught.
  assert(JSON.stringify(r.lineMarkers[1]) === '["Y"]',
    'uppercase `OBJ IDS=` recognized (case-insensitive)');
}

// -------- 7. ID list trimming + empty filtering --------
{
  const r = parseGrblJobLines([
    '; OBJ ids= a , b ,  ,c',
    'G0 X1',
  ]);
  assert(JSON.stringify(r.lineMarkers[0]) === '["a","b","c"]',
    'IDs trimmed; empty entries filtered out');
}

// -------- 8. comment lines without marker are dropped --------
{
  const r = parseGrblJobLines([
    '; Header generated by Output',
    '; Some preamble',
    'G0 X1',
  ]);
  assert(r.jobLines.length === 1 && r.jobLines[0] === 'G0 X1',
    'non-marker comments are silently dropped');
  assert(r.lineMarkers[0] === null,
    'non-marker comments do not produce markers');
}

// -------- 9. marker chains: only most recent attaches --------
{
  const r = parseGrblJobLines([
    '; OBJ ids=first',
    '; OBJ ids=second',
    'G0 X1',
  ]);
  assert(JSON.stringify(r.lineMarkers[0]) === '["second"]',
    'two markers in a row → only the most recent attaches');
}

// -------- 10. marker attaches only to next line, not all subsequent --------
{
  const r = parseGrblJobLines([
    '; OBJ ids=once',
    'G0 X1',
    'G0 X2',
    'G0 X3',
  ]);
  assert(JSON.stringify(r.lineMarkers[0]) === '["once"]',
    'first gcode line carries marker');
  assert(r.lineMarkers[1] === null && r.lineMarkers[2] === null,
    'subsequent lines carry null until a new marker appears');
}

// -------- 11. interleaved markers + gcode --------
{
  const r = parseGrblJobLines([
    '; OBJ ids=a',
    'G0 X1',
    'G1 X2',
    '; OBJ ids=b,c',
    'G1 X3',
    'G1 X4',
  ]);
  assert(r.jobLines.length === 4, 'four gcode lines preserved');
  assert(JSON.stringify(r.lineMarkers[0]) === '["a"]',
    'first gcode line tagged with a');
  assert(r.lineMarkers[1] === null,
    'second gcode line untagged');
  assert(JSON.stringify(r.lineMarkers[2]) === '["b","c"]',
    'third gcode line tagged with b,c');
  assert(r.lineMarkers[3] === null,
    'fourth gcode line untagged again');
}

// -------- 12. Source-level pin: GrblController delegates --------
{
  const here = dirname(fileURLToPath(import.meta.url));
  const ctrlSrc = readFileSync(
    resolve(here, '../src/controllers/grbl/GrblController.ts'),
    'utf-8',
  );
  assert(/from '\.\/GrblJobLineParser'/.test(ctrlSrc),
    'GrblController imports parseGrblJobLines from GrblJobLineParser');
  assert(/parseGrblJobLines\(lines\)/.test(ctrlSrc),
    'GrblController calls parseGrblJobLines(lines)');
  assert(/T1-134/.test(ctrlSrc),
    'GrblController carries T1-134 marker');
  // Pre-T1-134 inline regex literal is gone from the controller. The
  // regex now lives only in the parser module.
  assert(!/\/\^;\\s\*OBJ\\s\+ids=\(\.\+\)\$\/i/.test(ctrlSrc),
    'inline OBJ-id regex literal is gone from GrblController');

  const parserSrc = readFileSync(
    resolve(here, '../src/controllers/grbl/GrblJobLineParser.ts'),
    'utf-8',
  );
  assert(/T1-134/.test(parserSrc),
    'GrblJobLineParser carries T1-134 marker');
  assert(/export function parseGrblJobLines/.test(parserSrc),
    'parseGrblJobLines is exported');
}

console.log(`\nResult: ${passed} passed, ${failed} failed\n`);
if (failed > 0) process.exit(1);
