/**
 * T3-3: PROJECT_MAP.md is generated, not hand-maintained.
 *
 * Run: npx tsx tests/project-map-generated.test.ts
 */
import { readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';

let passed = 0;
let failed = 0;
function assert(c: boolean, m: string): void {
  if (c) {
    passed++;
    console.log(`  ✓ ${m}`);
  } else {
    failed++;
    console.error(`  ✗ ${m}`);
  }
}

console.log('\n=== T3-3 generated project map ===\n');

const ROOT = process.cwd();
const SCRIPT_PATH = resolve(ROOT, 'scripts/generate-project-map.mjs');
const PROJECT_MAP_PATH = resolve(ROOT, 'PROJECT_MAP.md');
const PACKAGE_JSON_PATH = resolve(ROOT, 'package.json');

const packageJson = JSON.parse(readFileSync(PACKAGE_JSON_PATH, 'utf-8')) as {
  scripts?: Record<string, string>;
};
const projectMap = readFileSync(PROJECT_MAP_PATH, 'utf-8');

assert(
  packageJson.scripts?.['project-map:generate'] === 'node scripts/generate-project-map.mjs',
  'package.json exposes project-map:generate script',
);
assert(
  packageJson.scripts?.['project-map:check'] === 'node scripts/generate-project-map.mjs --check',
  'package.json exposes project-map:check script',
);

assert(
  /AUTO-GENERATED by `npm run project-map:generate`/.test(projectMap),
  'PROJECT_MAP.md declares itself auto-generated',
);
assert(
  !/updated every time a file is added, modified, or deleted/i.test(projectMap),
  'stale manual-maintenance rule removed',
);
assert(
  !/41 source files, 9 test files/.test(projectMap),
  'stale source/test file counts removed',
);

const check = spawnSync(process.execPath, [SCRIPT_PATH, '--check'], {
  cwd: ROOT,
  encoding: 'utf-8',
});

assert(check.status === 0, `project-map --check exits 0 (status ${check.status ?? 'null'})`);
assert(
  /PROJECT_MAP\.md is up to date/.test(`${check.stdout}\n${check.stderr}`),
  'project-map --check reports up-to-date output',
);

console.log(`\nResult: ${passed} passed, ${failed} failed\n`);
process.exit(failed > 0 ? 1 : 0);
