// Non-HTML files the host serves: Cloudflare Pages headers, robots.txt and the
// sitemap.

// The site ships no JavaScript, so the policy denies scripts outright. Keep it
// in sync with website/tests/build.test.mjs, which asserts no page needs more.
const CONTENT_SECURITY_POLICY = [
  "default-src 'none'",
  "style-src 'self'",
  "img-src 'self'",
  "font-src 'self'",
  "base-uri 'none'",
  "form-action 'none'",
  "frame-ancestors 'none'",
  'upgrade-insecure-requests',
].join('; ');

export function headersFile() {
  return `# Generated by website/build.mjs. Cloudflare Pages response headers.
/*
  Content-Security-Policy: ${CONTENT_SECURITY_POLICY}
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Cross-Origin-Opener-Policy: same-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), serial=(), usb=(), interest-cohort=()
  Strict-Transport-Security: max-age=31536000

/assets/*
  Cache-Control: public, max-age=31536000, immutable
`;
}

export function robotsFile(origin) {
  const lines = ['User-agent: *', 'Allow: /'];
  if (origin) lines.push(`Sitemap: ${origin}/sitemap.xml`);
  return `${lines.join('\n')}\n`;
}

function xmlEscape(value) {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function sitemapFile(origin, pages) {
  const urls = pages
    .filter((page) => !page.noindex)
    .map((page) => `  <url><loc>${xmlEscape(new URL(page.path, origin).href)}</loc></url>`);
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join('\n')}
</urlset>
`;
}
