; Generated by LaserForge
; Job: rectangle-cut fixture
; Objects: 1, Layers: 1
G21 ; mm mode
G90 ; absolute positioning
M5 S0

; --- Cut (pass 1) ---
M8 ; air assist ON
; OBJ ids=mobm3vj3-3-59y8rq
G0 X30.000 Y120.000
M4 S800
G1 X70.000 Y120.000 F150 S800
G1 X70.000 Y100.000 S800
G1 X30.000 Y100.000 S800
G1 X30.000 Y120.000 S800
M5 S0
M9 ; air assist OFF

M5 S0
G0 X0.000 Y0.000 ; return to job origin
M2 ; program end