; Generated by LaserForge
; Job: rectangle-cut fixture
; Objects: 1, Layers: 1
G21 ; mm mode
G90 ; absolute positioning
M5 S0

; --- Cut (pass 1) ---
M8 ; air assist ON
G0 X0.000 Y20.000
M4 S800
G1 X40.000 Y20.000 F150 S800
G1 X40.000 Y0.000 S800
G1 X0.000 Y0.000 S800
G1 X0.000 Y20.000 S800
M5 S0
M9 ; air assist OFF

M5 S0
G0 X0.000 Y0.000 ; return to job origin
M2 ; program end