; Generated by LaserForge
; Job: rectangle-cut fixture
; Objects: 1, Layers: 1
G21 ; T2-14 safety baseline: mm mode
G17 ; T3-20 safety baseline: XY plane
G91 ; T2-14 safety baseline: relative positioning (Head mode)
G94 ; T3-20 safety baseline: feed per minute
M5 S0 ; T2-14 safety baseline: laser off at start

; --- Cut (pass 1) ---
M8 ; air assist ON
; OBJ ids=det-000003
; G0 skipped (no motion)
M4 S0
G1 X40.000 F150 S800
G1 Y-20.000 S800
G1 X-40.000 S800
G1 Y20.000 S800
M5 S0
M9 ; air assist OFF

M5 S0 ; T2-14 safety baseline: laser off at end
G90 ; restore absolute positioning
M2 ; T2-14 safety baseline: program end