; Generated by LaserForge
; Job: score-line fixture
; Objects: 1, Layers: 1
G21 ; mm mode
G90 ; absolute positioning
M5 S0

; --- Score (pass 1) ---
G0 X0.000 Y0.000
M4 S150
G1 X160.000 Y0.000 F2200 S150
M5 S0

M5 S0
M2 ; program end