; Generated by LaserForge
; Job: score-line fixture
; Objects: 1, Layers: 1
G21 ; T2-14 safety baseline: mm mode
G17 ; T3-20 safety baseline: XY plane
G91 ; T2-14 safety baseline: relative positioning (Head mode)
G94 ; T3-20 safety baseline: feed per minute
M5 S0 ; T2-14 safety baseline: laser off at start

; --- Score (pass 1) ---
; OBJ ids=det-000004
; G0 skipped (no motion)
M4 S150
G1 X160.000 F2200 S150
M5 S0

M5 S0 ; T2-14 safety baseline: laser off at end
G0 X-160.000 Y0.000 ; return to start
G90 ; restore absolute positioning
M2 ; T2-14 safety baseline: program end