import type { BoxLibraryPreset, BoxPresetCategory } from './boxLibraryTypes';

export type { BoxLibraryPreset, BoxPresetCategory } from './boxLibraryTypes';
export type BoxDimensionMode = 'outside' | 'inside';

export const BOX_PRESET_CATEGORIES: Array<{ id: BoxPresetCategory | 'all'; label: string }> = [
  { id: 'all', label: 'All' },
  { id: 'basic', label: 'Basic Boxes' },
  { id: 'tray', label: 'Open Trays' },
  { id: 'gift', label: 'Gift & Display' },
  { id: 'storage', label: 'Workshop & Storage' },
  { id: 'electronics', label: 'Electronics' },
  { id: 'calibration', label: 'Calibration' },
  { id: 'desk', label: 'Desk Organizers' },
];

type PresetInput = Omit<BoxLibraryPreset, 'sortOrder'> & { sortOrder?: number };

function preset(input: PresetInput, index: number): BoxLibraryPreset {
  return { ...input, sortOrder: input.sortOrder ?? index + 1 };
}

const PRESETS: PresetInput[] = [
  {
    id: 'small-keepsake-box',
    name: 'Small Keepsake Box',
    category: 'basic',
    description: 'Compact six-face starter box for small gifts, hardware, and first-fit validation.',
    tags: ['closed', 'starter', 'keepsake', 'gift'],
    width: 80,
    height: 50,
    depth: 40,
    thickness: 3,
    fingerWidth: 10,
    kerf: 0.1,
    fitAllowance: 0.03,
    openTop: false,
    lidType: 'flush',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Closed', 'Starter', 'Finger Joint'],
    recommendedUse: 'Use this first when you want a complete box, not a tray.',
    accentColor: '#00d4ff',
    previewVariant: 'closed-box',
  },
  {
    id: 'medium-utility-box',
    name: 'Medium Utility Box',
    category: 'basic',
    description: 'General-purpose closed box sized for workshop parts, cables, and small supplies.',
    tags: ['closed', 'utility', 'storage', 'medium'],
    width: 130,
    height: 70,
    depth: 90,
    thickness: 3,
    fingerWidth: 13,
    kerf: 0.1,
    fitAllowance: 0.04,
    openTop: false,
    lidType: 'flush',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Closed', 'Utility'],
    recommendedUse: 'A balanced default for everyday containers.',
    accentColor: '#6db8ff',
    previewVariant: 'closed-box',
  },
  {
    id: 'large-storage-box',
    name: 'Large Storage Box',
    category: 'basic',
    description: 'Larger six-face storage blank for lightweight bulky parts.',
    tags: ['closed', 'large', 'storage', 'bin'],
    width: 220,
    height: 120,
    depth: 150,
    thickness: 4,
    fingerWidth: 18,
    kerf: 0.12,
    fitAllowance: 0.06,
    openTop: false,
    lidType: 'flush',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Large', 'Closed'],
    recommendedUse: 'Scale only after proving fit with the calibration preset.',
    accentColor: '#5eead4',
    previewVariant: 'closed-box',
  },
  {
    id: 'open-parts-tray',
    name: 'Open Parts Tray',
    category: 'tray',
    description: 'Five-face tray for sorting screws, model parts, and laser-cut offcuts.',
    tags: ['open', 'tray', 'parts', 'sorting'],
    width: 120,
    height: 35,
    depth: 80,
    thickness: 3,
    fingerWidth: 12,
    kerf: 0.1,
    fitAllowance: 0.04,
    openTop: true,
    lidType: 'none',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Open Top', 'Tray'],
    recommendedUse: 'Fast utility tray for a first useful burn.',
    accentColor: '#2dd4a0',
    previewVariant: 'open-tray',
  },
  {
    id: 'desk-organizer-tray',
    name: 'Desk Organizer Tray',
    category: 'tray',
    description: 'Low open tray for stationery, clips, and daily desk clutter.',
    tags: ['desk', 'tray', 'organizer', 'open'],
    width: 180,
    height: 35,
    depth: 120,
    thickness: 3,
    fingerWidth: 15,
    kerf: 0.1,
    fitAllowance: 0.05,
    openTop: true,
    lidType: 'none',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Open Top', 'Desk'],
    recommendedUse: 'Good for drawer and desktop inserts.',
    accentColor: '#a78bfa',
    previewVariant: 'open-tray',
  },
  {
    id: 'drawer-insert-tray',
    name: 'Drawer Insert Tray',
    category: 'tray',
    description: 'Wide shallow tray intended to drop into a drawer cavity.',
    tags: ['drawer', 'insert', 'tray', 'storage'],
    width: 240,
    height: 35,
    depth: 160,
    thickness: 3,
    fingerWidth: 16,
    kerf: 0.1,
    fitAllowance: 0.05,
    openTop: true,
    lidType: 'none',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Drawer', 'Open Top'],
    recommendedUse: 'Measure the drawer interior and use inside mode if exact fit matters.',
    accentColor: '#38bdf8',
    previewVariant: 'open-tray',
  },
  {
    id: 'premium-gift-box',
    name: 'Premium Gift Box',
    category: 'gift',
    description: 'Polished closed gift blank with balanced proportions for engraving.',
    tags: ['gift', 'display', 'closed', 'premium'],
    width: 140,
    height: 70,
    depth: 90,
    thickness: 3,
    fingerWidth: 14,
    kerf: 0.1,
    fitAllowance: 0.03,
    openTop: false,
    lidType: 'lift-off',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Gift', 'Lift-off Lid'],
    recommendedUse: 'Engrave the lid before assembly for a finished presentation box.',
    accentColor: '#f59e0b',
    previewVariant: 'gift-box',
  },
  {
    id: 'display-presentation-box',
    name: 'Display Presentation Box',
    category: 'gift',
    description: 'Wide low display box for samples, ornaments, and product presentations.',
    tags: ['display', 'presentation', 'gift', 'closed'],
    width: 180,
    height: 55,
    depth: 110,
    thickness: 3,
    fingerWidth: 15,
    kerf: 0.1,
    fitAllowance: 0.04,
    openTop: false,
    lidType: 'lift-off',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Display', 'Gift'],
    recommendedUse: 'Use contrasting veneer or engraving for the lid.',
    accentColor: '#fb7185',
    previewVariant: 'gift-box',
  },
  {
    id: 'tea-sachet-box',
    name: 'Tea Sachet Box',
    category: 'gift',
    description: 'Medium box sized for sachets, tea bags, and small craft stock.',
    tags: ['tea', 'sachet', 'gift', 'storage'],
    width: 95,
    height: 65,
    depth: 70,
    thickness: 3,
    fingerWidth: 12,
    kerf: 0.1,
    fitAllowance: 0.04,
    openTop: false,
    lidType: 'flush',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Gift', 'Storage'],
    recommendedUse: 'A small practical gift box with room for branding.',
    accentColor: '#f97316',
    previewVariant: 'gift-box',
  },
  {
    id: 'screw-bits-box',
    name: 'Screw Bits Box',
    category: 'storage',
    description: 'Small rugged storage box for bits, drivers, screws, and shop consumables.',
    tags: ['screws', 'bits', 'workshop', 'storage'],
    width: 110,
    height: 45,
    depth: 70,
    thickness: 3,
    fingerWidth: 10,
    kerf: 0.1,
    fitAllowance: 0.05,
    openTop: false,
    lidType: 'flush',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Workshop', 'Closed'],
    recommendedUse: 'Label the lid after generation for repeatable shop bins.',
    accentColor: '#94a3b8',
    previewVariant: 'closed-box',
  },
  {
    id: 'cable-storage-box',
    name: 'Cable Storage Box',
    category: 'storage',
    description: 'Deeper box for USB leads, adapters, and coiled cables.',
    tags: ['cable', 'storage', 'workshop', 'desk'],
    width: 180,
    height: 75,
    depth: 120,
    thickness: 3,
    fingerWidth: 15,
    kerf: 0.1,
    fitAllowance: 0.05,
    openTop: false,
    lidType: 'lift-off',
    bottomStyle: 'standard',
    handleStyle: 'slot',
    featureBadges: ['Storage', 'Handle Slots'],
    recommendedUse: 'Add text labels to side faces after generation.',
    accentColor: '#60a5fa',
    previewVariant: 'closed-box',
  },
  {
    id: 'workshop-bin',
    name: 'Workshop Bin',
    category: 'storage',
    description: 'Open bin with hand slots for fast-access shop organization.',
    tags: ['workshop', 'bin', 'open', 'handles'],
    width: 200,
    height: 90,
    depth: 130,
    thickness: 4,
    fingerWidth: 18,
    kerf: 0.12,
    fitAllowance: 0.06,
    openTop: true,
    lidType: 'none',
    bottomStyle: 'standard',
    handleStyle: 'slot',
    featureBadges: ['Open Top', 'Handle Slots'],
    recommendedUse: 'Best for larger plywood stock after fit calibration.',
    accentColor: '#22c55e',
    previewVariant: 'open-tray',
  },
  {
    id: 'arduino-enclosure',
    name: 'Arduino Enclosure',
    category: 'electronics',
    description: 'Small electronics project box for controller boards, sensors, and wiring.',
    tags: ['arduino', 'electronics', 'enclosure', 'project'],
    width: 80,
    height: 35,
    depth: 55,
    thickness: 3,
    fingerWidth: 8,
    kerf: 0.1,
    fitAllowance: 0.06,
    openTop: false,
    lidType: 'lift-off',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Electronics', 'Lift-off Lid'],
    recommendedUse: 'Cut access holes after generating the base enclosure.',
    accentColor: '#14b8a6',
    previewVariant: 'electronics-box',
  },
  {
    id: 'ventilated-project-box',
    name: 'Ventilated Project Box',
    category: 'electronics',
    description: 'Electronics enclosure previewed with vent slots for warm components.',
    tags: ['electronics', 'vent', 'project', 'enclosure'],
    width: 120,
    height: 45,
    depth: 80,
    thickness: 3,
    fingerWidth: 10,
    kerf: 0.1,
    fitAllowance: 0.06,
    openTop: false,
    lidType: 'lift-off',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Electronics', 'Vent Slots'],
    recommendedUse: 'Vent marks are visual guidance; add actual vents after generation.',
    accentColor: '#06b6d4',
    previewVariant: 'electronics-box',
  },
  {
    id: 'power-supply-box',
    name: 'Power Supply Box',
    category: 'electronics',
    description: 'Larger electronics housing for bench modules and power supply prototypes.',
    tags: ['electronics', 'power', 'supply', 'vent'],
    width: 160,
    height: 70,
    depth: 110,
    thickness: 3,
    fingerWidth: 14,
    kerf: 0.1,
    fitAllowance: 0.07,
    openTop: false,
    lidType: 'lift-off',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Electronics', 'Vent Slots'],
    recommendedUse: 'Verify airflow and clearances before final material.',
    accentColor: '#0ea5e9',
    previewVariant: 'electronics-box',
  },
  {
    id: 'fit-test-mini-box',
    name: 'Fit-test Mini Box',
    category: 'calibration',
    description: 'Tiny sacrificial box for proving kerf, fit allowance, and tab depth.',
    tags: ['fit', 'test', 'calibration', 'mini'],
    width: 45,
    height: 28,
    depth: 35,
    thickness: 3,
    fingerWidth: 7,
    kerf: 0.1,
    fitAllowance: 0.05,
    openTop: true,
    lidType: 'none',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Calibration', 'Open Top'],
    recommendedUse: 'Burn this before scaling to a full-size box.',
    accentColor: '#facc15',
    previewVariant: 'test-coupon',
  },
  {
    id: 'finger-joint-test-coupon',
    name: 'Finger Joint Test Coupon',
    category: 'calibration',
    description: 'Flat coupon for checking side-to-side finger fit without burning a full box.',
    tags: ['coupon', 'finger', 'fit', 'calibration'],
    width: 80,
    height: 18,
    depth: 30,
    thickness: 3,
    fingerWidth: 8,
    kerf: 0.1,
    fitAllowance: 0.05,
    openTop: true,
    lidType: 'none',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Coupon', 'Calibration'],
    recommendedUse: 'Use when tuning fit allowance only.',
    accentColor: '#fde047',
    previewVariant: 'test-coupon',
  },
  {
    id: 'kerf-calibration-coupon',
    name: 'Kerf Calibration Coupon',
    category: 'calibration',
    description: 'Small coupon intended for measuring beam width and fit behavior.',
    tags: ['kerf', 'coupon', 'calibration', 'measure'],
    width: 90,
    height: 20,
    depth: 30,
    thickness: 3,
    fingerWidth: 9,
    kerf: 0.1,
    fitAllowance: 0.03,
    openTop: true,
    lidType: 'none',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Kerf', 'Calibration'],
    recommendedUse: 'Measure cut results with calipers and update kerf presets.',
    accentColor: '#eab308',
    previewVariant: 'test-coupon',
  },
  {
    id: 'pencil-cup',
    name: 'Pencil Cup',
    category: 'desk',
    description: 'Tall open-top desk cup for pens, brushes, tools, and craft sticks.',
    tags: ['pencil', 'cup', 'desk', 'open'],
    width: 70,
    height: 110,
    depth: 70,
    thickness: 3,
    fingerWidth: 10,
    kerf: 0.1,
    fitAllowance: 0.04,
    openTop: true,
    lidType: 'none',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Desk', 'Open Top'],
    recommendedUse: 'A useful tall test after the mini fit box succeeds.',
    accentColor: '#c084fc',
    previewVariant: 'pencil-cup',
  },
  {
    id: 'card-holder-box',
    name: 'Card Holder Box',
    category: 'desk',
    description: 'Small open holder for business cards, labels, and index cards.',
    tags: ['card', 'desk', 'holder', 'open'],
    width: 100,
    height: 45,
    depth: 55,
    thickness: 3,
    fingerWidth: 10,
    kerf: 0.1,
    fitAllowance: 0.04,
    openTop: true,
    lidType: 'none',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Desk', 'Cards'],
    recommendedUse: 'Good for branded countertop holders.',
    accentColor: '#818cf8',
    previewVariant: 'open-tray',
  },
  {
    id: 'business-note-box',
    name: 'Business Note Box',
    category: 'desk',
    description: 'Desk box for sticky notes, receipts, and small paper stock.',
    tags: ['desk', 'notes', 'paper', 'storage'],
    width: 105,
    height: 50,
    depth: 105,
    thickness: 3,
    fingerWidth: 10,
    kerf: 0.1,
    fitAllowance: 0.04,
    openTop: true,
    lidType: 'none',
    bottomStyle: 'standard',
    handleStyle: 'none',
    featureBadges: ['Desk', 'Open Top'],
    recommendedUse: 'Size fits common note pads with a little room.',
    accentColor: '#a78bfa',
    previewVariant: 'open-tray',
  },
];

export const BOX_LIBRARY_PRESETS: BoxLibraryPreset[] = PRESETS
  .map(preset)
  .sort((a, b) => a.sortOrder - b.sortOrder);

export function getBoxPresetById(id: string): BoxLibraryPreset | undefined {
  return BOX_LIBRARY_PRESETS.find(p => p.id === id);
}

export function getBoxLibraryPreset(id: string): BoxLibraryPreset | undefined {
  return getBoxPresetById(id);
}

export function formatBoxLibraryCategory(category: BoxPresetCategory): string {
  return BOX_PRESET_CATEGORIES.find(c => c.id === category)?.label ?? category;
}

export function filterBoxPresets(
  presets: BoxLibraryPreset[],
  query: string,
  category: BoxPresetCategory | 'all',
): BoxLibraryPreset[] {
  const words = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  return presets
    .filter(preset => category === 'all' || preset.category === category)
    .filter(preset => {
      if (words.length === 0) return true;
      const haystack = [
        preset.name,
        preset.description,
        preset.category,
        formatBoxLibraryCategory(preset.category),
        preset.recommendedUse ?? '',
        ...preset.tags,
        ...preset.featureBadges,
      ].join(' ').toLowerCase();
      return words.every(word => haystack.includes(word));
    })
    .sort((a, b) => a.sortOrder - b.sortOrder);
}
