/**
 * Run each test file in its own Node process. Prevents leaked timers/intervals
 * (e.g. GRBL status polling) from keeping `npm test` running indefinitely.
 */
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(root, '..');
const tsxCli = join(projectRoot, 'node_modules', 'tsx', 'dist', 'cli.mjs');

const testEnv = {
  ...process.env,
  LASERFORGE_DETERMINISTIC_IDS: '1',
};

const files = [
  'deterministic-ids.test.ts',
  'pipeline.test.ts',
  'plan-optimizer-large-raster.test.ts',
  'controller.test.ts',
  'controller-fresh-status-recheck.test.ts',
  'controller-bounds-recheck.test.ts',
  'simulation.test.ts',
  'viewport.test.ts',
  'wake-lock.test.ts',
  'svg-import.test.ts',
  'svg-import-placement.test.ts',
  'placement.test.ts',
  'history.test.ts',
  'history-entry-metadata.test.ts',
  'job-log-quota.test.ts',
  'joblog-storage-migration.test.ts',
  'jobreplay-storage-migration.test.ts',
  'scene-io.test.ts',
  'ui-integration.test.ts',
  'autosave-serialization.test.ts',
  'autosave-storage.test.ts',
  'autosave-preserves-images.test.ts',
  'autosave-dirty-flag-on-failure.test.ts',
  'manual-save-needs-acknowledgement.test.ts',
  'delete-marks-dirty.test.ts',
  'text-property-edits-undoable.test.ts',
  'undo-redo-invalidation.test.ts',
  'selection-restore-on-history.test.ts',
  'text-outline-cache.test.ts',
  'source-text-migration.test.ts',
  'preflight-bounds.test.ts',
  'preflight-negative-coords.test.ts',
  'gcode-template-validator.test.ts',
  'preflight-template-validation.test.ts',
  'storage-adapter-contract.test.ts',
  'storage-filesystem-unit.test.ts',
  'storage-ipc-no-broad-clear.test.ts',
  'dialog-open-file-size-limit.test.ts',
  'dialog-open-no-full-path.test.ts',
  'electron-navigation-blocked.test.ts',
  'electron-renderer-sandbox.test.ts',
  'security-deps-pinned.test.ts',
  'storage-singleton.test.ts',
  'entitlement-storage-migration.test.ts',
  'entitlement-api-split.test.ts',
  'recovery-failure-alerts.test.tsx',
  'recovery-eligibility-non-empty-cases.test.ts',
  'active-layer-history-consistent.test.ts',
  'start-mode-labels.test.ts',
  'job-mode-plan-summary.test.ts',
  'compile-race-guard.test.ts',
  'auto-detect-includes-max-spindle.test.ts',
  'entitlement-api-migration-phase2a.test.ts',
  'entitlement-api-migration-phase2b.test.ts',
  'connect-button-mutex.test.tsx',
  'entitlement-api-no-deprecated-export.test.ts',
  'connect-cleanup-on-partial-failure.test.ts',
  'connect-abort-signal.test.ts',
  'pause-resume-stop-surface-errors.test.ts',
  'frame-current-mode-emits-first-move.test.ts',
  'right-origin-x-flip.test.ts',
  'tester-verification-no-secret.test.ts',
  'tester-secret-not-in-source.test.ts',
  'dev-build-self-check.test.ts',
  'packaged-app-no-dev-arg.test.ts',
  'production-bundle-smoke.test.ts',
  'source-maps-not-shipped.test.ts',
  'source-maps-hidden-mode.test.ts',
  'native-deps-prebuild-check.test.ts',
  'execution-coordinator.test.ts',
  'execution-coordinator-unlock-home-frame.test.ts',
  'execution-coordinator-testfire-setorigin.test.ts',
  'execution-coordinator-deadman.test.ts',
  'execution-coordinator-autofocus.test.ts',
  'execution-coordinator-disconnect.test.ts',
  'device-profile-storage-migration.test.ts',
  'device-profile-basic-api.test.ts',
  'validated-job-ticket-phase1.test.ts',
  'validated-job-ticket-mismatch.test.ts',
  'jobcompiler-strips-pro-settings-without-license.test.ts',
  'jobcompiler-keeps-pro-settings-with-license.test.ts',
  'nesting-throws-without-license.test.ts',
  'boolean-ops-throws-without-license.test.ts',
  'service-layer-pro-gate-coverage.test.ts',
  'preflight.test.ts',
  'raster-m4-no-software-splitting.test.ts',
  'job-compiler-curve-flatness.test.ts',
  'controller-stop-safety.test.ts',
  'stop-on-error-override.test.ts',
  'safety-off-two-stage.test.ts',
  'safety-write-failure-surfaces.test.ts',
  'machine-service-laser-state-subscription.test.ts',
  'error-handler-sends-safety-off.test.ts',
  'error-handler-faults-active-job.test.ts',
  'machine-settings-stop-on-error-toggle.test.ts',
  'autofocus.test.ts',
  'machine-service-pause-resume.test.ts',
  'machine-service-start-validated-job.test.ts',
  'machine-service-job-lifecycle-safety.test.ts',
  'failed-start-persists-log.test.ts',
  'job-outcome-enum-failed-to-start.test.ts',
  'job-replay-capture-not-gated.test.ts',
  'start-validated-job-passes-context.test.ts',
  'active-job-canvas-context-pinned.test.ts',
  'active-job-canvas-context-cleared.test.ts',
  'try-finalize-respects-observed-running.test.ts',
  'try-finalize-after-observed-running.test.ts',
  'start-validated-job-then-immediately-tryfinalize.test.ts',
  'wcs-mutation-consent.test.ts',
  'wcs-no-listener-blocks-job.test.ts',
  'wcs-no-listener-headless-flag.test.ts',
  'scene-transaction-unified.test.ts',
  'scene-transaction-app-wired.test.ts',
  'scene-commit-actions-wired.test.ts',
  'modal-confirm-with-checkbox.test.tsx',
  'console-input.test.tsx',
  'laser-mode-banner.test.tsx',
  'ui-start-job-uses-ticket.test.tsx',
  'connection-panel-preflight-no-loop.test.tsx',
  'usecompilemanager-stale-no-loop.test.tsx',
  'numberinput-no-loop-on-rapid-prop-change.test.tsx',
  'numberinput-tolerance-still-works.test.tsx',
  'numberinput-focused-not-overridden.test.tsx',
  'falcon-serial-profile.test.ts',
  'falcon-autofocus-heal.test.ts',
  'falcon-ws-frame-cap.test.ts',
  'material-preset-schema.test.ts',
  'material-library-storage.test.ts',
  'material-presets-storage.test.ts',
  'material-feedback-storage.test.ts',
  'streaming-health.test.ts',
  'grbl-system-line-tagging.test.ts',
  'command-classifier.test.ts',
  'machine-service-user-sendcommand.test.ts',
  'plan-marker-emission.test.ts',
  'output-marker-encoding.test.ts',
  'grbl-marker-lifecycle.test.ts',
  'materials.test.ts',
  'response-curve.test.ts',
  'calibration-grid.test.ts',
  'calibrate-dialog.test.ts',
  'calibration-analyzer.test.ts',
  'raster-with-curve.test.ts',
  'image-processing.test.ts',
  'image-prep-grayscale-equivalence.test.ts',
  'dither-cache-key-content-hash.test.ts',
  'import-callback-identity-stable.test.tsx',
  'image-processing-worker-equivalence.test.ts',
  'start-readiness-panel.test.tsx',
  'frame-idle-timeout-dynamic.test.ts',
  'savedorigin-not-compile-invalidating.test.ts',
  'machine-plan-bounds-source.test.ts',
  'run-frame-fail-fast-on-blocked-command.test.ts',
  'exact-idle-gates.test.ts',
  'preflight-output-layer-filter.test.ts',
  'pause-emits-m5-after-feed-hold.test.ts',
  'no-electron-sendgcode-export.test.ts',
  'frame-dot-finally-emits-m5.test.ts',
  'footer-m5-appended-at-send.test.ts',
  'no-scene-canvas-in-machine-coord.test.ts',
  'jog-and-setorigin-state-after-confirm.test.ts',
  'operation-ordering.test.ts',
  'test-grid-generator.test.ts',
  'box-geometry.test.ts',
  'box-joinery-v2.test.ts',
  'box-library.test.ts',
  'box-preset-preview-model.test.ts',
  'box-library-filtering.test.tsx',
  'box-generator-library-integration.test.tsx',
  'box-dimension-modes.test.ts',
  'kerf-presets.test.ts',
  'velocity-profile.test.ts',
  'plan-accel-sanity.test.ts',
  'scene-canvas-machine-coord-check.test.ts',
  'no-localstorage-in-core.test.ts',
  'no-gcode-in-ui.test.ts',
  'burn-moves-2d.test.ts',
  'scanning-offset.test.ts',
  'smart-overscan.test.ts',
  'gcode-templates.test.ts',
  'gcode-templates-safety.test.ts',
  'gcode-template-sanitization.test.ts',
  'gcode-relative-mode.test.ts',
  'ui-start-job-preserves-markers.test.ts',
  'gcode-relative-return-template.test.ts',
  'origin-mode-wcs-zero.test.ts',
  'bed-height-resolver-parity.test.ts',
  'start-mode-wcs-reset.test.ts',
  'fonts.test.ts',
  'frame-gcode-pure.test.ts',
  'frame-gcode-crosshair.test.ts',
  'frame-required-before-start.test.ts',
  'simulator-view-ymirror.test.ts',
  'runner-registration-coverage.test.ts',
  'connection-panel-offset-button-disabled.test.ts',
  'app-version-from-package.test.ts',
  'ticket-validation-message-translation.test.ts',
  'output-deterministic-with-clock-injection.test.ts',
  'no-live-pro-flag-writes.test.ts',
  'customstart-mode-reassertion.test.ts',

  // E2E snapshot tests
  'e2e/rectangle-cut.test.ts',
  'e2e/text-bundled-inter.test.ts',
  'e2e/text-hershey-sans.test.ts',
  'e2e/engrave-fill.test.ts',
  'e2e/score-line.test.ts',
  'e2e/mixed-scene.test.ts',
  'e2e/origin-absolute.test.ts',
  'e2e/origin-saved.test.ts',
  'e2e/circle-cut.test.ts',
  'e2e/multi-pass-cut.test.ts',
  'e2e/large-scene.test.ts',
];

for (const f of files) {
  // stderr so it appears even when stdout is fully buffered
  console.error(`\n▶ ${f}\n`);
  const r = spawnSync(process.execPath, [tsxCli, join(projectRoot, 'tests', f)], {
    cwd: projectRoot,
    env: testEnv,
    stdio: 'inherit',
    windowsHide: true,
  });
  const code = r.status === null ? 1 : r.status;
  if (code !== 0) {
    process.exit(code);
  }
}

process.exit(0);
