/**
 * === FILE: /src/core/output/Output.ts ===
 * 
 * Purpose:    The Output is Stage 3 of the pipeline: Plan → Output.
 *             An Output is a DEVICE-SPECIFIC representation of the plan.
 *             Could be G-code text, Ruida binary, or any other format.
 *             This is the final stage before sending to hardware.
 * 
 * Pipeline:   Plan → [generateOutput()] → Output → [controller.sendJob()] → Machine
 * 
 * Dependencies: /src/core/types.ts
 * Last updated: Phase 5, Step 18 — Plan Optimizer (added laserOn/laserOff encoding)
 */

import { generateId } from '../types';

// ─── OUTPUT FORMAT ───────────────────────────────────────────────

export type OutputFormat = 'grbl' | 'marlin' | 'smoothie' | 'ruida' | 'custom';

// ─── OUTPUT ──────────────────────────────────────────────────────

export interface Output {
  readonly id: string;
  planId: string;
  format: OutputFormat;
  createdAt: string;

  // Text-based formats (G-code)
  text: string | null;
  lineCount: number;

  // Binary formats (Ruida)
  binary: Uint8Array | null;

  fileSizeBytes: number;
}

// ─── OUTPUT STRATEGY INTERFACE ───────────────────────────────────
/**
 * Strategy pattern for device-specific output generation.
 * Each machine protocol implements this interface.
 * The Plan → Output conversion is delegated to the strategy.
 */

import { type Plan, type Move } from '../plan/Plan';
import { type Job } from '../job/Job';
import { type GcodeGenerateOptions } from './GcodeOrigin';

export type { GcodeGenerateOptions, GcodeStartMode } from './GcodeOrigin';

export interface OutputStrategy {
  readonly formatId: OutputFormat;
  readonly formatName: string;

  // Generate full output from a plan
  generate(plan: Plan, job: Job, options?: GcodeGenerateOptions): Output;

  // Individual move encoding (used by generate internally)
  encodeHeader(job: Job): string;
  encodeRapid(to: { x: number; y: number }): string;
  encodeLinear(to: { x: number; y: number }, power: number, speed: number): string;
  encodeLaserOn(power: number): string;
  encodeLaserOff(): string;
  encodeDwell(ms: number): string;
  encodeAirAssist(on: boolean): string;
  encodeZMove(z: number): string;
  encodeFooter(job: Job): string;
}

// ─── STRATEGY REGISTRY ───────────────────────────────────────────

const strategies = new Map<OutputFormat, OutputStrategy>();

export function registerOutputStrategy(strategy: OutputStrategy): void {
  strategies.set(strategy.formatId, strategy);
}

export function getOutputStrategy(format: OutputFormat): OutputStrategy | undefined {
  return strategies.get(format);
}

export function listOutputFormats(): OutputFormat[] {
  return [...strategies.keys()];
}

// ─── BASE GCODE STRATEGY ─────────────────────────────────────────
/**
 * Base implementation for G-code based controllers.
 * GRBL and Marlin extend this with their specific differences.
 */
export abstract class BaseGCodeStrategy implements OutputStrategy {
  abstract readonly formatId: OutputFormat;
  abstract readonly formatName: string;

  // Subclasses override these for protocol differences
  abstract encodeLaserOn(power: number): string;
  abstract encodeLaserOff(): string;
  abstract encodePowerValue(power: number): string;

  private currentSpeed = 0;

  generate(plan: Plan, job: Job, _options?: GcodeGenerateOptions): Output {
    this.currentSpeed = 0;

    try {
      const lines: string[] = [];

      lines.push(this.encodeHeader(job));

      for (const op of plan.operations) {
        const srcOp = job.operations.find(o => o.id === op.operationId);
        const passes = Math.max(1, srcOp?.settings.passes ?? 1);
        lines.push('');
        if (passes > 1) {
          lines.push(`; --- ${op.layerName} (pass ${op.passIndex + 1}/${passes}) ---`);
        } else {
          lines.push(`; --- ${op.layerName} (pass ${op.passIndex + 1}) ---`);
        }

        for (const move of op.moves) {
          lines.push(this.encodeMove(move));
        }
      }

      lines.push('');
      lines.push(this.encodeFooter(job));

      const text = lines.filter(l => l !== undefined).join('\n');

      return {
        id: generateId(),
        planId: plan.id,
        format: this.formatId,
        createdAt: new Date().toISOString(),
        text,
        lineCount: lines.length,
        binary: null,
        fileSizeBytes: new TextEncoder().encode(text).length,
      };
    } finally {
      this.currentSpeed = 0;
    }
  }

  encodeHeader(job: Job): string {
    return [
      `; Generated by LaserForge`,
      `; Job: ${job.name}`,
      `; Date: ${new Date().toISOString()}`,
      `; Objects: ${job.metadata.objectCount}, Layers: ${job.metadata.layerCount}`,
      'G21 ; mm mode',
      'G90 ; absolute positioning',
      this.encodeLaserOff(),
    ].join('\n');
  }

  encodeRapid(to: { x: number; y: number }): string {
    return `G0 X${to.x.toFixed(3)} Y${to.y.toFixed(3)}`;
  }

  encodeLinear(to: { x: number; y: number }, power: number, speed: number): string {
    const parts = [`G1 X${to.x.toFixed(3)} Y${to.y.toFixed(3)}`];
    if (speed !== this.currentSpeed) {
      parts.push(`F${speed.toFixed(0)}`);
      this.currentSpeed = speed;
    }
    parts.push(this.encodePowerValue(power));
    return parts.join(' ');
  }

  encodeDwell(ms: number): string {
    return `G4 P${(ms / 1000).toFixed(3)}`;
  }

  encodeAirAssist(on: boolean): string {
    return on ? 'M8 ; air assist ON' : 'M9 ; air assist OFF';
  }

  encodeZMove(z: number): string {
    return `G0 Z${z.toFixed(3)}`;
  }

  encodeFooter(_job: Job): string {
    return [
      this.encodeLaserOff(),
      'G0 X0.000 Y0.000 ; return to origin',
      'M2 ; program end',
    ].join('\n');
  }

  private encodeMove(move: Move): string {
    switch (move.type) {
      case 'rapid':    return this.encodeRapid(move.to);
      case 'linear':   return this.encodeLinear(move.to, move.power, move.speed);
      case 'laserOn':  return this.encodeLaserOn(move.power);
      case 'laserOff': return this.encodeLaserOff();
      case 'dwell':    return this.encodeDwell(move.ms);
      case 'setAir':   return this.encodeAirAssist(move.on);
      case 'setZ':     return this.encodeZMove(move.z);
    }
  }
}
