export { isElectronRenderer, type ElectronDetectionEnv } from './is-electron';
export { createDesktopPreviewUpdateAdapter } from './preview-updates';
export { createDesktopProjectFiles } from './desktop-project-files';
export { createDesktopLicenceAdapter } from './licensing';
export { createDesktopSupportLogReader } from './support-log';
export { createDesktopJobActivityReporter } from './job-activity';
export { createDesktopWindowCommands } from './desktop-window';
export { createDesktopSerialAdapter } from './desktop-serial';
export { createDesktopMachineNetwork } from './desktop-machine-network';
export { createDesktopAiAssistant } from './desktop-ai';
