/**
 * T1-134: pure G-code job-line + object-id marker parser extracted
 * from `GrblController._parseJobLines`. Pre-T1-134 this method lived
 * inside the 2664-line controller. It is pure (no `this` access) and
 * the parsing rule it encodes is the contract for how OBJ-id comment
 * markers map gcode lines back to scene objects — important enough to
 * unit-test in isolation rather than only through controller mocks.
 *
 * The marker grammar is single-line: a comment of the form
 * `; OBJ ids=a,b,c` (case-insensitive, optional spaces around the
 * separator) attaches the next non-comment gcode line to the listed
 * object IDs. Once attached the marker is consumed — subsequent gcode
 * lines need their own `; OBJ ids=` marker to be tagged.
 *
 * Empty / whitespace-only lines are dropped (matches the controller's
 * pre-T1-134 `line.trim().length === 0` filter). Comment lines that
 * don't match the OBJ-id pattern are silently skipped — same behavior
 * as pre-T1-134 (e.g. `; Header generated by ...` lines that the
 * output strategy emits before the job body).
 *
 * Output keeps the same shape `{ jobLines, lineMarkers }` the
 * controller consumes — `jobLines[i]` and `lineMarkers[i]` are paired
 * 1:1 so an ack for line `i` can be resolved to its OBJ-id set.
 */

/** Parsed job representation: gcode lines + parallel OBJ-id markers. */
export interface ParsedJobLines {
  jobLines: string[];
  lineMarkers: (readonly string[] | null)[];
}

const OBJ_IDS_COMMENT_RE = /^;\s*OBJ\s+ids=(.+)$/i;

export interface GrblJobLineParserState {
  pendingMarker: readonly string[] | null;
}

export function createGrblJobLineParserState(): GrblJobLineParserState {
  return { pendingMarker: null };
}

export function parseGrblJobLineChunk(
  lines: ReadonlyArray<string>,
  state: GrblJobLineParserState = createGrblJobLineParserState(),
): ParsedJobLines {
  const jobLines: string[] = [];
  const lineMarkers: (readonly string[] | null)[] = [];
  for (const raw of lines) {
    const line = raw.trim();
    if (line.length === 0) continue;
    if (line.startsWith(';')) {
      const m = line.match(OBJ_IDS_COMMENT_RE);
      if (m) {
        state.pendingMarker = m[1].split(',').map((s) => s.trim()).filter((s) => s.length > 0);
      }
      continue;
    }
    jobLines.push(line);
    lineMarkers.push(state.pendingMarker);
    state.pendingMarker = null;
  }
  return { jobLines, lineMarkers };
}

/**
 * Split `lines` into a parallel `jobLines` / `lineMarkers` pair.
 *
 * Behavior:
 *   - Whitespace-only lines are dropped (trimmed-empty test).
 *   - Lines starting with `;` are comments — only `; OBJ ids=...` is
 *     interpreted; all others are dropped.
 *   - When a marker is parsed, the NEXT non-comment line carries those
 *     IDs. Subsequent lines without their own marker carry `null`.
 *   - Markers do not chain: two `; OBJ ids=...` lines in a row
 *     overwrite — only the most recent one attaches.
 */
export function parseGrblJobLines(lines: ReadonlyArray<string>): ParsedJobLines {
  return parseGrblJobLineChunk(lines);
}
